name: companies_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/paulfaid/MWNZ_Dart

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  test_process: ^2.1.0
  xml: ^6.3.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
